{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app.name }}-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - {{ .Values.persistence.accessmode }} 
  resources:
    requests:
      storage: {{ .Values.persistence.storage }}
{{- end }} 
