apiVersion: katalog.m4d.ibm.com/v1alpha1
kind: Asset
metadata:
  name: diabetes-json
spec:
  secretRef: 
    name: diabetes-json
  assetDetails:
    dataFormat: csv
    connection:
      type: s3
      s3:
        endpoint: “http://minio:9000”
        bucket: “minio-bucket”
        objectKey: “my-secret”
  assetMetadata:
    geography: UK
    tags:
    - health
    componentsMetadata:
      Id: 
        tags:
        - PII

