data:
{{- if .Values.copy -}}
    {{- if .Values.copy.source.connection.kafka }}
      WP2_TOPIC: {{ .Values.copy.source.connection.kafka.topic_name }}
      HEIR_KAFKA_HOST: {{ .Values.copy.source.connection.kafka.bootstrap_servers }}  
    {{- end }}
    {{- if .Values.copy.destination.connection.s3 }}
      S3_URL: {{if not (contains "://" .Values.copy.destination.connection.s3.endpoint)}} https://{{end}}{{ .Values.copy.destination.connection.s3.endpoint }}
      credentials:
        secretPath: {{ .Values.copy.source.vault.secretPath }}
      SECRET_NSPACE: {{ .Values.copy.destination.credentialLocation.namespace }}
      SECRET_FNAME: {{ .Values.copy.destination.credentialLocation.secret_file }}       
    {{- end }}
    {{- if .transformations }}
    transformations:
    {{- $redactColumns := list -}}
    {{- $statisticsColumn := list -}}
    {{- range .transformations -}}
      {{- if eq .name "RedactAction" -}}
        {{- $redactColumns = .RedactAction.columns -}}
      {{- end -}}
      {{- if eq .name "RemoveAction" -}}
        {{- $removeColumns = .RemoveAction.columns -}}
      {{- end -}}
    {{- end -}}    
    {{- if $redactColumns }}    
      - action: "RedactColumn"
        description: "redact columns: {{ $redactColumns }}"
        columns: 
          {{- range $redactColumns}}
          - {{ . }}
          {{- end }}
        options:
          redactValue: "XXXXX"
    {{- end }}
    {{- if $statisticsColumn }}
      - action: "Statistics"
        description: "Perform statistical analysis: {{ $statisticsColumn }}"
        columns: 
          {{- range $statisticsColumn}}
          - {{ . }}
          {{- end }}
    {{- end }}
    {{- end }}
{{- end -}}
