# Default values for hello-world-read-module.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image: 
  repository:  ghcr.io/elsalant/sql-to-fhir
  tag: v1
  pullPolicy: Always
  pullSecret: null

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

read:
  # Read source
  source:
    connection:
      name: csv
    credentialLocation: 
    format: json
  transformations:
  - name: RedactColumn
    RedactColumn:
      columns:
      - col1
  - name: Statistics
    Statistics:
      columns:
      - col1
  destination:
  # write destination
    connection:
      name: s3
      s3:
        bucket: 
        endpoint: 
        object_key: 
      type: 2
    credentialLocation: 
      namespace: fybrik-system
      secret_file: credentials-els
    format: csv
    vault:
      address:
      authPath: 
      role: 
      secretPath: 

nodeSelector: {}

tolerations: []

affinity: {}
