{{- if .Values.read -}}
data:
{{- range .Values.read }}
  {{- if .source.connection.kafka }}
    WP2_TOPIC: {{ .source.connection.kafka.topic_name }}
    HEIR_KAFKA_HOST: {{ .source.connection.kafka.bootstrap_servers }}  
  {{- end }}
  {{- if .transformations }}
   transformations:
   {{- $redactColumns := list -}}
   {{- $statisticsColumn := list -}}
   {{- $removeColumns := list -}}
   {{- $blockColumns := list -}}
   {{- range .transformations }}
     {{- if eq .name "RemoveColumn" -}}
       {{- $removeColumns = .RemoveColumn.columns }}
         - action: "RemoveColumn"
           description: "Remove columns: {{ $removeColumns }}"
           columns:
             {{- range $removeColumns}}
             - {{ . }}
             {{- end }}
     {{- end -}}
     {{- if eq .name "Statistics" -}}
       {{- $statisticsColumn = .Statistics.columns }}
       - action: "Statistics"
         description: "Perform statistical analysis on: {{ $statisticsColumn }}"
         columns:
           {{- range $statisticsColumn}}
           - {{ . }}
           {{- end }}
     {{- end -}}
     {{- if eq .name "blockColumns" -}}
       {{- $blockColumns = .Statistics.columns }}
       - action: "blockColumns"
         description: "Block all data for resource: {{ $blockColumns }}"
         columns:
           {{- range $blockColumns}}
           - {{ . }}
           {{- end }}
     {{- end -}}
     {{- if eq .name "RedactColumn" -}}
       {{- $redactColumns = .RedactColumn.columns }}
       - action: "RedactColumn"
         description: "redact columns: {{ $redactColumns }}"
         columns:
           {{- range $redactColumns}}
           - {{ . }}
           {{- end }}
         options:
           redactValue: "XXXXX"
     {{- end -}} 
   {{- end -}}   
   {{- end }}
 {{- end }} 
{{- end -}}
