apiVersion: app.fybrik.io/v1alpha1
kind: FybrikStorageAccount
metadata:
  name: account-eliot
  namespace: fybrik-system
spec:
  endpoint: http://s3.eu.cloud-object-storage.appdomain.cloud
  secretRef: credentials-els
  regions:
    - UK

