apiVersion: katalog.fybrik.io/v1alpha1
kind: Asset
metadata:
  name: diabetes-json
  namespace: mvp
spec:
  secretRef: 
    name: diabetes-json
  assetDetails:
    dataFormat: json
    connection:
      type: kafka
      kafka: 
        topic_name: fhir-wp2
        bootstrap_servers: "kafka.fybrik-system:9092"
  assetMetadata:
    geography: UK
    tags:
    - healthcare
    componentsMetadata:
      valueQuantity.value:
        tags:
        - stats
