apiVersion: katalog.fybrik.io/v1alpha1
kind: Asset
metadata:
  name: diabetes-json
  namespace: mvp
spec:
  details:
    dataFormat: json
    connection:
      name: fhir
      fhir:
        fhirServer: ibmfhir
        port: 9443
        namespace: mvp
        kafka_topic_name: fhir-wp2
        kafka_bootstrap_servers: "kafka.fybrik-system:9092"
  secretRef: 
    name: diabetes-json
  metadata:
    name: FHIR server
    geography: UK
    tags:
      healthcare: true
    columns:
      - name: valueQuantity.value
        tags:
          stats: true
          PII: false
          blocked: false
