kind: Secret
apiVersion: v1
metadata:
  name: credentials-els
  namespace: fybrik-system
stringData:
  access_key_id: "6560XXXXX"
  secret_access_key: "4e95XXXXX"
  accessKeyID: "65608XXXXX"
  secretAccessKey: "4e956XXXXX"
type: Opaque

