# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: app.fybrik.io/v1alpha1
kind: FybrikModule
metadata:
  name: fhir-to-s3
  labels:
    name: fhirToS3
    version: 0.1.0 
spec:
  type:  service  
  capabilities:
    - supportedInterfaces:
        - source: 
            protocol: kafka    
            dataformat: json
          sink: 
            protocol: s3
            dataformat: csv
      actions:
      - name: RedactColumn
      - name: Statistics
      capability: copy
  chart:
    name: ghcr.io/elsalant/fhir-to-s3-chart:0.0.2
  statusIndicators:
    - kind: StreamTransfer
      successCondition: status.status == SUCCEEDED
      failureCondition: status.status == FAILED
      errorMessage: status.error

