# Copyright 2020 IBM Corp.
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: app.fybrik.io/v1alpha1
kind: FybrikModule
metadata:
  name: fhir-to-s3
  labels:
    name: fhirToS3
    version: 0.1.0 
  namespace: fybrik-system
spec:
  type:  service  
  capabilities:
   - capability: copy
     actions:
       - name: RedactColumn
       - name: Statistics
     api:
       connection:
         name: fhir
         fhir:
           fhirServer: ibmfhir
           port: 9443
           namespace: mvp
           secretRef: diabetes-json
           kafka_topic_name: fhir-wp2
           kafka_bootstrap_servers: "kafka.fybrik-system:9092"
       dataFormat: json
     supportedInterfaces:
        - source: 
            protocol: fhir    
            dataformat: json
          sink: 
            protocol: s3
            dataformat: csv
  chart:
    name: ghcr.io/elsalant/fhir-to-s3-chart:0.0.2
    values:
      image.tag: v1
  statusIndicators:
    - kind: StreamTransfer
      successCondition: status.status == SUCCEEDED
      failureCondition: status.status == FAILED
      errorMessage: status.error

