apiVersion: app.fybrik.io/v1alpha1
kind: FybrikApplication
metadata:
  name: healthdemo
  namespace: mvp
  labels:
    app: mvp-notebook
    requestedBy: EliotSalant
spec:
  selector: 
    workloadSelector: {} 
  appInfo:
    intent: mvp-demo
  data:
    - dataSetID: "mvp/diabetes-json"
      requirements:
        copy:
          required: true
        interface: 
          protocol: s3
          dataformat: csv
